### ISSUE TITLE
Ability to add attribute to include only marked classes

### ISSUE THREAD

**Issue by PrimaForge** [SpatialFocus/AddSetter.Fody#2]
Just wanted to say great library I have been looking for something similar for awhile.

I see you have the ability to only include namespaces you put in the FODY file. But, I was wondering If the ability could be added so that we could add a attribute to a specific class and include them that way. Something like below

    [AddSetter]
    public class Person
    {
        public string Name { get; } 
    }

And it would only include classes marked by that attribute. That would be great.

**Comment by pergerch** [comment]
Sure, sounds like a good idea. Let's see if Santa will be able to make you this present 🎄

**Comment by pergerch** [comment]
Hi @FutureTD, the attribute is now included in v1.1 of our package. 

We've decided to introduce a new attribute `<SpatialFocus.AddSetter DoNotIncludeByDefault='True'/>` to maintain backward compatibility. After switching off the IncludeByDefault, you will be able to mark the classes you want to include with the `[AddSetter]` attribute. See readme or tests for details. 

I hope that helps.

**Comment by PrimaForge** [comment]
Thank you
